### ISSUE TITLE
DatailView show verbose name

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#10]
A sugestion to beter the detail view render

In tags.py

@register.filter
def get_verbose_field_name(instance, field_name):
    return instance._meta.get_field(field_name).verbose_name.title()

In object_detail.html
remove
{{field.name|undertospaced}}
add
{{object|get_verbose_field_name:field.name}}

new detail view show too verbose_name

**Comment by marcoshemann** [comment]
more one, to show CHOICES

in tag.py
change

def get_value(obj, field):
    try:
        return getattr(obj, 'get_%s_display' % field)()
    except:
        return getattr(obj, field)

**Comment by asifpy** [comment]
Perfect. Create PR and merge your changes.

**Comment by marcoshemann** [comment]
thank you
