### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#11]
Hi,
I am using signals to do a process if is create and other process if is update.
but when o update a record, the crud run post_update_signal AND post_create_signal too.
Inside of singn function how i know if is create or update?

Regards

**Comment by asifpy** [comment]
As per my implementation, `post_create_signal` is for **CreateView** and `post_update_signal` is for **UpdateView**. How its running both signals when you are updating record? You customized anything?.

During update it will run only `post_update_signal`.
