### ISSUE TITLE
Crud with proxy model issue

### ISSUE THREAD

**Issue by paolodina** [asifpy/django-crudbuilder#12]
I'm not sure this applies to you too or if it's some kind of issue in my project. Sorry in advance in this case.

I need to associate the crud to a proxy model. This proxy model extends a model defined in another app. In this scenario I get a rather long exception running runserver, fixed adding a fallback method to get the model back from ContentType. Unfortunately I can't provide a test case, if you would to have a look at the patch anyway, please refer here:

https://github.com/paolodina/django-crudbuilder/commit/de8db9d2169a6c4f369d259bcde25f2808a0249f

**Comment by asifpy** [comment]
Perfect. Create PR and merge your changes.
