### ISSUE TITLE
Error in builder = ViewBuilder

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#15]
Now , in this version when I run:

from crudbuilder.views import ViewBuilder
builder = ViewBuilder('cadastro', 'cadastro', 'CadastroCrud')
builder.generate_crud()
I take this error:
 File "/home/wm.0.2/lib/python3.4/site-packages/crudbuilder/abstract.py", line 78, in get_inlineformset
    if self.crud.inlineformset:
AttributeError: 'str' object has no attribute 'inlineformset'

In CadastroCrud there are 

inlineformset = None

I try but I dosent find a error.

Regards,

**Comment by asifpy** [comment]
The latest version doesn't handle the extendability. I will look into the error which you sent and update the code based on that.

**Comment by marcoshemann** [comment]
This is ok now.
