### ISSUE TITLE
Multiple builders for same model

### ISSUE THREAD

**Issue by flaiming** [asifpy/django-crudbuilder#26]
I lack the ability to create multiple crudbuilders for one model. Since URL is tied to the app name and model name, this is not currently possible. 
I'm proposing adding new attribute to crudbuilder called `model_url_name`, which would override default model plural name, used in URL.

Example:

``` python
class TestModelCrud(BaseCrudbuilder):
    model = TestModel
    # this would give URL /<appname>/testmodel/

class TestSameModelCrud(BaseCrudbuilder):
    model = TestModel
    model_url_name = 'testmodel2'
    # this would give URL /<appname>/testmodel2/
```

Or it could get model URL name from crudbuilder class name, which would be maybe even simpler.

What do you think?

**Comment by asifpy** [comment]
So you mean the same crudbuilder with different URL? What's the use case here? I would say we should give ability to change entire URL instead of just changing the model name in the current URL. (Let developer select whatever URL he wants to pick)

**Comment by flaiming** [comment]
Use case: I have Company model with different type of companies in it. I want to have one crudbuilder to list and modify and bunch of other crudbuilders just for view to focus on different aspects of these data (certain type of company, different style of data display). 
I could build just simple django ListView, but than I would lose ability to sort by columns and do fulltext search with minimum code.

Ability to change entire URL would be the best, I'll work on that.

**Comment by asifpy** [comment]
@flaiming: Check this  [Example for multiple builder](https://github.com/asifpy/django-crudbuilder/blob/master/example/example/crud.py#L44,) where you can define multiple builders for the same model.
