### ISSUE TITLE
custom_modelform

### ISSUE THREAD

**Issue by avaldevilap** [asifpy/django-crudbuilder#3]
I need use two forms, one for add and other for update. If you can fix it. Thk

**Comment by asifpy** [comment]
Use the [example/forms.py](https://github.com/asifpy/django-crudbuilder/blob/master/example/example/forms.py) where I defined two separate forms for CREATE and UPDATE, at the same time you also need to modify the [crud.py](https://github.com/asifpy/django-crudbuilder/blob/master/example/example/crud.py#L35) to specify your CREATE/UPDATE forms.
