### ISSUE TITLE
Feature request for "inline" adding/editing related objects

### ISSUE THREAD

**Issue by TheRaspyDev** [asifpy/django-crudbuilder#33]
Hi

I found django-crudbuilder when I was looking for a generic implementation of CRUD forms.
It looks very promising and easy to understand.

The only thing I'm missing in django-crudbuilder is the possibility for "inline" editing/adding a related object (as in django admin).

On my research I found django-addanother (https://github.com/jonashaag/django-addanother) which supplies exactly this functionality in a small app.

Would it be possible to add this functionality to django-crudbuilder either by using/referencing the django-addanother app or by implementing this directly into django-crudbuilder?

Regards

**Comment by asifpy** [comment]
We shouldn't add more hard dependencies like `django-addanother`, which makes hard to maintain the current package. However you can use `django-addanother` with `django-crudbuilder` by adding custome model forms. I already added example which uses both. You can find it here [django-addanother with crudbuilder](https://github.com/asifpy/django-quickstart/commit/ba4e44c5e6784d0e7f24897d42be7339ab9780ec)
