### ISSUE TITLE
Unclear on TableBuilder

### ISSUE THREAD

**Issue by oziek88** [asifpy/django-crudbuilder#39]
I'm looking to add checkboxes to my table in list.html.  I saw the commented out override instructions. But I'm still a little unclear to how it ties into my ViewBuilder.  Do I reference the CustomTable in a specific way in views?  Thank you.  

This is my tables.py:

```
builder = TableBuilder('sorter', 'foo', FooCrud)
CheckboxFooTable = builder.generate_table()
class CustomFooTable(CheckboxFooTable):
	selection = tables.CheckBoxColumn(accessor='pk')

	class Meta:
		model = foo
		attrs = {'id': 'foo-crud-table'}
                sequence = ('selection', 'name', 'gender')
```

**Comment by asifpy** [comment]
You can create your own custom table (as shown here [Custom table example](https://github.com/asifpy/django-crudbuilder/commit/efcb62f3248cd175b131c7367d62d13cd823be62#diff-5bb324613f6772db2dda37cb0bd84823)), and set the same table for `custom_table2` field in your crud class.

Check out my latest [commit](https://github.com/asifpy/django-crudbuilder/commit/efcb62f3248cd175b131c7367d62d13cd823be62) where I added same example on how to handle custom tables

**Comment by oziek88** [comment]
Thank you for the quick response.  That makes a lot more sense to me.  I'm having an issue with importing my table to crud though.  I haven't had this issue with any other .py files. It's like crud.py won't allow the import of anything from my tables.py file.  Have you experienced this, or should I do some digging?

**Comment by asifpy** [comment]
There shouldn't be any problem, you can check in example [crud.py](https://github.com/asifpy/django-crudbuilder/blob/master/example/example/crud.py#L5) where I'm importing `CustomPersonTable` in `crud.py` and everything is working fine

**Comment by oziek88** [comment]
It was a blooper on my part. I was importing a crudbuilder file into my tables.py. All figured out. Thank you so much
