### ISSUE TITLE
Error in model field image

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#5]
I am using a model with a field image
(models.py)
Cadastro
logo = models.ImageField(upload_to = gera_caminho_cad, blank=True)

in view.py
class CadastroCrud(BaseCrudBuilder):
    model = Cadastro
    modelform_excludes = ['logo']
...

And when i click Id in list view, to show me detail view, i get this error:

Exception Value:	
The 'imagem' attribute can only be accessed from Contato instances.
Exception Location:	/home/wm.0.2/lib/python3.4/site-packages/django/db/models/fields/files.py in __get__, line 176

Error during template rendering

In template /home/wm.0.2/des/cadastro/templates/cadastro/crud/crud_detail.html, error at line 27

Template
27	        {% for field in object|get_model_fields %}    <-- ERROR

**Comment by asifpy** [comment]
Template tag error resolved here : https://github.com/asifpy/django-crudbuilder/commit/5cf7654780e101d1749233e8b760a21a16f88db9#diff-7965a9755a9fbd3f48eaddc1ff376cd4

**Comment by marcoshemann** [comment]
Perfect, thank you. Congratulations for the project.
