### ISSUE TITLE
Include erro in Django >1.10

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#55]
Hi Asifpy
I detect a import error using with Django > 1.10
In view.py line 1
#from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy
Regards

**Comment by marcoshemann** [comment]
More one
in mixins.py line  34

#if not request.user.is_authenticated():
if not request.user.is_authenticated:

**Comment by asifpy** [comment]
`django.core.urlresolvers` and `is_authenticated()` will continue to work until Django 2.0 for backwards compatibility. Currently `crudbuilder` supports 1.11
