### ISSUE TITLE
Erro in work with models managed=False

### ISSUE THREAD

**Issue by marcoshemann** [asifpy/django-crudbuilder#56]
Hi Asif,
I got a error when I want create a crud with a table with managed = False, and manually set like   app_label = 'portal_db', in this case, show this error: ( if possible, help me to fix this)

File "/home/devteam/.pyenv/versions/mh-lab2/lib/python3.5/site-packages/crudbuilder/abstract.py", line 52, in get_model_class
    c = ContentType.objects.get(app_label=self.app, model=self.model)
  File "/home/devteam/.pyenv/versions/mh-lab2/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/devteam/.pyenv/versions/mh-lab2/lib/python3.5/site-packages/django/db/models/query.py", line 401, in get
    self.model._meta.object_name
django.contrib.contenttypes.models.DoesNotExist: ContentType matching query does not exist.

During handling of the above exception, another exception occurred:

**Comment by asifpy** [comment]
Seems like the ContentType is not created for your `un-managed` model. Make sure to perform the below steps:

- ./manage.py inspectdb to check the existing table
- Copy the model class and place it your models.py with managed=False and db_table
- Run ./manage.py makemigrations
- Run ./manage.py migrate (this will create new content type for your unmanaged model)

**Comment by marcoshemann** [comment]
Tks, but the solution to fix this is create a APP with name portal_db, add in INSTALLED_APPS. 
 portal_db is the name of second db ( non default) .
