### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by oniseijin** [asifpy/django-crudbuilder#58]
Currently, Djanjo 2 support seems WIP

I had to switch back to 1.11 due to the deprecation of django.core.urlresolvers. This is imported by urls module of crudbuilder. Should be an easy fix, but care has to be taken to support both. 

See more at https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers

**Comment by asifpy** [comment]
Which version of `crudbuilder` are you using? I suggest you to install it directly from Github.
Refer this #57

**Comment by oniseijin** [comment]
At the time of writing it was the latest version in pypi,  and I had done what was mentioned in #57, but I'll take your word that the latest source is good to go :)
