### ISSUE TITLE
LOGIN_REQUIRED_FOR_CRUD not honored for registered cruds page

### ISSUE THREAD

**Issue by jorgehatccrma** [asifpy/django-crudbuilder#59]
When setting `LOGIN_REQUIRED_FOR_CRUD = True` in `settings.py`, the models' cruds are correctly blocked when not logged in, but it is still possible to see the list of registered cruds at the `myapp.com/crud/` url. Is there a config flag to make this view also hidden when not logged in?

**Comment by asifpy** [comment]
Resolved here: https://github.com/asifpy/django-crudbuilder/commit/19906014223cc55106891352a9aae4aea2315b73
