### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by flaiming** [asifpy/django-crudbuilder#75]
Hi, will there be new release version any time soon?

**Comment by nikolas-dev** [comment]
@flaiming did you solve `TypeError: PersonTable.model = <Person: > (type Person), but type must be one of (ModelBase)`

**Comment by flaiming** [comment]
@nikolas-dev You mean issue https://github.com/asifpy/django-crudbuilder/issues/67 ? As far is I know it's related to django-tables2 checking so I created issue https://github.com/jieter/django-tables2/issues/775 there with potential fix, but so far no response from maintainer.

**Comment by russell310** [comment]
@flaiming please check https://github.com/asifpy/django-crudbuilder/pull/76

**Comment by flaiming** [comment]
Yes, that fixed it.

**Comment by nikolas-dev** [comment]
@russell310 Thanks. Working

**Comment by nikolas-dev** [comment]
@russell310 @flaiming please add this feature https://github.com/asifpy/django-crudbuilder/issues/77
